server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yihongbo123/spring-cloud-microservice-study.git/     # 配置git仓库的地址
          search-paths: config                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 757430916@qq.com                                             # git仓库的账号
          password: bobo52464251                                            # git仓库的密码