server:
  port: 8055
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yihongbo123/spring-cloud-microservice-study.git     # 配置git仓库的地址
          search-paths: config                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 757430916@qq.com                                             # git仓库的账号
          password: bobo52464251
    stream:
      kafka:
        binder:
          zk-nodes: 172.18.44.122:2181
          brokers: 172.18.44.122:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/

security:
  user:
    name: user
    password: 123456

## 发送http://host:port/bus/refresh刷新时，关闭安全验证
management:
  security:
     enabled: false

