server:
  port: 8000
spring:
  application:
    name: microservice-provider-user # 项⽬名称尽量⽤⼩写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: # 指定数据源
    platform: h2 # 指定数据源类型
    schema: classpath:schema.sql # 指定h2数据库的建表脚本
    data: classpath:data.sql # 指定h2数据库的insert脚本

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # 指定注册中⼼的地址

  instance:
    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
    preferIpAddress: true