server:
  port: 9090
spring:
  application:
    name: spring-boot-admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://172.18.44.120:8761/eureka/,http://172.18.44.128:8761/eureka/
  instance:
    hostname: 172.18.42.65
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}