server:
  port: 8761  # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://172.17.14.145:8761/eureka/
  server:
    enable-self-preservation: false
#    eviction-interval-timer-out-ms: 4000
---
spring:
  profiles: eureka1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1                               # 指定当profile=peer1时，主机名
  client:
    serviceUrl:
      defaultZone: http://172.18.44.123:8761/eureka/      # 将自己注册到peer2这个Eureka上面去
#  server:
#    enable-self-preservation: false            # 设为false，关闭自我保护
#    eviction-interval-timer-out-ms: 15000      # 清理间隔（单位毫秒，默认是60*1000）

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://172.18.44.122:8761/eureka/
#  server:
#      enable-self-preservation: false            # 设为false，关闭自我保护
#      eviction-interval-timer-out-ms: 15000      # 清理间隔（单位毫秒，默认是60*1000）



