server:
  port: 8001
spring:
  application:
    name: microservice-provider-user # 项⽬名称尽量⽤⼩写
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource: # 指定数据源
#    platform: h2 # 指定数据源类型
#    schema: classpath:schema.sql # 指定h2数据库的建表脚本
#    data: classpath:data.sql # 指定h2数据库的insert脚本

#logging:
#  level:
#    root: INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/ # 指定注册中⼼的地址
  instance:
    # leaseExpirationDurationInSeconds，表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    lease-expiration-duration-in-seconds: 10
    # leaseRenewalIntervalInSeconds，表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance。除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。默认30秒
    lease-renewal-interval-in-seconds: 5

master:
  datasource:
    url: jdbc:mysql://172.18.44.122:3306/cloudTest?useUnicode=true&characterEncoding=utf8
    username: testuser
    password: test@tgw
    driverClassName: com.mysql.jdbc.Driver

#测试随机数
aa:
  value: 15558888