spring:
  cloud:
    loadbalancer:
      retry:
      #该参数用来开启重试的机制
        enabled: true

    # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整
ribbon:
  eureka:
    enabled: true         # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka


#Hystrix全局超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

cloud-base-service-customer:
  ribbon:
    #请求连接的超时时间
    ConnectTimeout: 500
    #请求处理的超时时间
    ReadTimeout: 10000
    #对所有操作请求都进行重试
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 2
    #对当前实例的重试次数
    MaxAutoRetries: 1
cloud-base-service-user:
  ribbon:
    #请求连接的超时时间
    ConnectTimeout: 500
    #请求处理的超时时间
    ReadTimeout: 10000
    #对所有操作请求都进行重试
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 2
    #对当前实例的重试次数
    MaxAutoRetries: 1


logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug

#Dalston.SR3版本,spring cloud是默认关闭Hystrix的断路器功能
feign:
  hystrix:
    enabled: true








