spring:
  redis:
    cluster:
      nodes: 172.18.44.120:6380,172.18.44.128:6380,172.18.44.123:6380,172.18.44.120:6381,172.18.44.128:6381,172.18.44.123:6381

#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource: # 指定数据源
#    platform: h2 # 指定数据源类型
#    schema: classpath:schema.sql # 指定h2数据库的建表脚本
#    data: classpath:data.sql # 指定h2数据库的insert脚本

#logging:
#  level:
#    root: INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.itmuch.youran.persistence: ERROR

#  instance:
#    # leaseExpirationDurationInSeconds，表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
#    lease-expiration-duration-out-seconds: 10
#    # leaseRenewalIntervalInSeconds，表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance。除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。默认30秒
#    lease-renewal-interval-out-seconds: 5

#mapper:
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:26257/bank?sslmode=disable
#    username: maxroach
#    password:
#    driverClassName: org.postgresql.Driver
mapper:
  datasource:
    url: jdbc:mysql://172.18.44.120:3306/cloudTest?useUnicode=true&characterEncoding=utf8
    username: testuser
    password: testuser
    driverClassName: com.mysql.jdbc.Driver

security:
  user:
    name: user
    password: 123456


#测试随机数
aa:
  value: {cipher}'AQA1DWDoJcGQH2Boh7K2atJaIgSL72piGzBWM5RWigbyCAKwMJHZJhxwojEZGdC3G17pulf5PQPGYJ24N3SN2GLb4vHBBr3DiLe+s+qmg4DE61R3FsJ7ulhQKyuNW+9nCSjV3mXCTQgrmHh4zQmiHkK9LGNz9EbBNW9jg49fPJDHeZ2OGmuF4FqzqqI6hmSIrCJ4KjJ4bMIrEPHGakOrN4WpTUAXRqXFZA8eXHMHMmOFRmhcp6jFrM6VuEBmIeA11j7Tg2M7cOMxUj/4aPW83ZUzvzXqsbgWhHBaGv73zMQxltEu+FJBsR8s0zJEvpJ7soItPHrdP9vsfUhapQf0IQifSlWrS0DR1LWJbXoHEZiEjt3ulT55hdixkNlLZndMTsI='



