spring:
  datasource:
    url: jdbc:mysql://172.18.44.120:3306/cloudTest?useUnicode=true&characterEncoding=utf8
    username: testuser
    password: test@tgw88
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 172.18.44.122:6381
        - 172.18.44.122:6382
        - 172.18.44.123:6381
  jpa:
    hibernate:
#      DefaultNamingStrategy这个直接映射，不会做过多的处理（前提没有设置@Table，@Column等属性的时候）。
#      ImprovedNamingStrategy 表名，字段为小写，当有大写字母的时候会转换为分隔符号“_”。
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #如果数据库没有表就创建，有数据表如果结构发生就更新
      ddl-auto: update

#测试随机数
aa:
  value: 77777
