spring:
  datasource:
    url: jdbc:mysql://172.18.44.122:3306/cloudTest?useUnicode=true&characterEncoding=utf8
    username: testuser
    password: test@tgw88
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 172.18.44.122:6381
        - 172.18.44.122:6382
        - 172.18.44.123:6381
  jpa:
    hibernate:
#      DefaultNamingStrategy这个直接映射，不会做过多的处理（前提没有设置@Table，@Column等属性的时候）。
#      ImprovedNamingStrategy 表名，字段为小写，当有大写字母的时候会转换为分隔符号“_”。
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #如果数据库没有表就创建，有数据表如果结构发生就更新
      ddl-auto: update
  cloud:
    loadbalancer:
      retry:
      #该参数用来开启重试的机制
        enabled: true

    # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整
ribbon:
  eureka:
    enabled: true         # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka


#Hystrix全局超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

cloud-service-feign-user:
  ribbon:
    #请求连接的超时时间
    ConnectTimeout: 500
    #请求处理的超时时间
    ReadTimeout: 2000
    #对所有操作请求都进行重试
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 2
    #对当前实例的重试次数
    MaxAutoRetries: 1


logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug

#Dalston.SR3版本,spring cloud是默认关闭Hystrix的断路器功能
feign:
  hystrix:
    enabled: true








