spring:
  cloud:
    loadbalancer:
      retry:
      #该参数用来开启重试的机制
        enabled: false

#Hystrix全局超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

microservice-provider-user:
  ribbon:
    #请求连接的超时时间
    ConnectTimeout: 500
    #请求处理的超时时间
    ReadTimeout: 1500
    #对所有操作请求都进行重试
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 2
    #对当前实例的重试次数
    MaxAutoRetries: 1

zuul:
  # 需要忽视的服务(配置后将不会被路由)
  ignored-services: microservice-provider-user
  routes:
    # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
    movie:
      # 想要映射到的路径
      path: /movie/**
      # Eureka中的serviceId
      service-id: microservice-consumer-movie-ribbon-with-hystrix
    feign:
      path: /feignn/**
      service-id: MICROSERVICE-CONSUMER-MOVIE-FEIGN-WITH-HYSTRIX-STREAM