#spring:
#  cloud:
#    loadbalancer:
#      retry:
#      #该参数用来开启重试的机制
#        enabled: true
#  application:
#    name: microservice-consumer-movie-feign-with-hystrix-stream
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
#  instance:
#    hostname: feign
#    # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整
#ribbon:
#  eureka:
#    enabled: true         # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka
#
##Hystrix全局超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#microservice-provider-user:
#  ribbon:
#    #请求连接的超时时间
#    ConnectTimeout: 500
#    #请求处理的超时时间
#    ReadTimeout: 1500
#    #对所有操作请求都进行重试
#    OkToRetryOnAllOperations: true
#    #切换实例的重试次数
#    MaxAutoRetriesNextServer: 2
#    #对当前实例的重试次数
#    MaxAutoRetries: 1
#
#
#
#
#
##service-B:
##  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
