spring:
  application:
    name: cloud-stream-kafka-consumer
  cloud:
    stream:
      instanceCount: 1
      instanceIndex: 0
      kafka:
        binder:
          brokers: 172.18.44.122:9092
          zk-nodes: 172.18.44.122:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        input:
          destination: wsh-topic-01
          group: s3
          consumer:
            concurrency: 1
            partitioned: false

server:
  port: 8888